apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: grocery-app
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    kubelet:
      tlsVerify: false
  features:      
    apm:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: false
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true
  override:
    nodeAgent:
      env:
        - name: "DD_LOGS_CONFIG_FORCE_USE_TCP"
          value: "false"
        - name: "DD_IGNORE_AUTOCONF"
          value: "etcd kube_scheduler kube_controller_manager"
        
    clusterAgent:
      replicas: 1
      extraConfd:
        configDataMap:
          postgres.yaml: |-
            cluster_check: true
            advanced_ad_identifiers: 
              - kube_service:
                  name: "postgres-service"
                  namespace: "default"
            init_config:
            instances:
              - dbm: true
                host: "%%host%%"
                port: 5432              
                username: "datadog"
                password: "datadog"



