apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: grocery-app
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    kubelet:
      tlsVerify: false
  features:      
    apm:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: false
      containerCollectAll: false
      containerCollectUsingFiles: true
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true
  override:
    nodeAgent:
      env:
        - name: "DD_LOGS_CONFIG_FORCE_USE_TCP"
          value: "false"
        - name: "DD_IGNORE_AUTOCONF"
          value: "etcd kube_scheduler kube_controller_manager"
        - name: "DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION"
          value: "true"  
      containers:
        agent:
          volumeMounts: 
            - name: pointdir
              mountPath: /opt/datadog-agent/run
            - name: auditdir
              mountPath: /var/log/kubernetes/apiserver
            - name: dd-agent-config
              mountPath: /etc/datadog-agent/conf.d/kubernetes_audit.d
      volumes: 
        - name: pointdir
          hostPath:
            path: /opt/datadog-agent/run
        - name: auditdir
          hostPath:
            path: /var/log/kubernetes/apiserver
        - name: dd-agent-config
          configMap:
            name: dd-agent-config
            items:
              - key: kubernetes-audit-log
                path: conf.yaml        
    clusterAgent:
      replicas: 1
      extraConfd:
        configDataMap:
          postgres.yaml: |-
            cluster_check: true
            advanced_ad_identifiers: 
              - kube_service:
                  name: "postgres-service"
                  namespace: "default"
            init_config:
            instances:
              - dbm: true
                host: "%%host%%"
                port: 5432              
                username: "datadog"
                password: "datadog"
                reported_hostname: postgres_grocery

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dd-agent-config
  namespace: default
data:
  kubernetes-audit-log: |-
    logs:
      - type: file
        path: /var/log/kubernetes/apiserver/audit.log
        source: kubernetes.audit
        service: audit