apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    tags.datadoghq.com/service: "panda"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      annotations:
        author: "Manuel"
        ad.datadoghq.com/flask-app.logs: |
          [{
            "source": "flask",
            "service": "grocery-app",
            "tags": ["list:mum_list"],
            "log_processing_rules": [{
              "type": "exclude_at_match",
              "name": "exclude_handlers_logs",
              "pattern": "244"
            }]
          }]
      labels:
        app: flask-app
        tags.datadoghq.com/service: "panda"
        tags.datadoghq.com/flask-app.service: "grocery"
        tags.datadoghq.com/dummy-container.service: "test2"
        admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods part of this deployment
    spec:
      containers:
        - name: flask-app
          image: localhost:5000/flask-app:latest
          ports:
            - containerPort: 5000
          env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/flask-app.service']
          - name: DD_TRACE_DEBUG
            value: "true"      
          - name: DD_TRACE_AGENT_URL
            value: 'unix:///var/run/datadog/apm.socket'  
          volumeMounts:
          - name: apmsocketpath
            mountPath: /var/run/datadog  
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
        - name: dummy-container
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/dummy-container.service']
          resources:
            limits:
              cpu: "0.1"
              memory: "128Mi"      
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
---
apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000


