apiVersion: v1
kind: PersistentVolume
metadata:
  name: applogs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/applogs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: applogs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
