steps:
  - label: "Test"
    command: |
      bash -c "
        set -e
        python3 -m venv venv
        source venv/bin/activate
        pip install -r flask/requirements.txt
        flake8 flask/
        pytest flask/
      "
    key: test

  - label: "Build and push docker image to docker hub"
    command: |
      docker build -t manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7} -f flask/Dockerfile flask
      docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
      docker push manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7}
    key: build
    depends_on: test

  - label: "Deploy to minikube"
    command: |
      kubectl config use-context minikube
      kubectl set image deployment/flask-app flask-app=manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7}
    key: deploy
    depends_on: build
