steps:
  - label: "🔍 Lint & Test"
    command: |
      pip install -r flask/requirements.txt
      flake8 flask/
      pytest flask/
    key: test

  - label: "🐳 Build & Push Docker Image to Docker Hub"
    command: |
      docker build -t manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7} .
      echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      docker push manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7}
    key: build
    depends_on: test

  - label: "🚀 Deploy to Minikube"
    command: |
      kubectl config use-context minikube
      kubectl set image deployment/flask-app flask-app=manueltattolo/flask-app:${BUILDKITE_COMMIT:0:7}
    key: deploy
    depends_on: build
